export const LDAP_URL = 'https://oege.ie.hva.nl/~vddxx/ldapper/index.php'
export const BACKEND_URL = 'http://localhost:4000'
export const TRIBE_ENDPOINT = 'tribes'
export const SQUAD_ENDPOINT = 'squads'
export const ACCOUNT_ENDPOINT = 'users'
export const AGREEMENTS_ENDPOINT = 'agreements'
