// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const awsConfig = {
  Auth: {
    // REQUIRED - Amazon Cognito Identity Pool ID
    identityPoolId: 'eu-west-1:027d449a-b82b-4bd8-8fdb-981895db3398',
    // REQUIRED - Amazon Cognito Region
    region: 'eu-west-1',
    // OPTIONAL - Amazon Cognito User Pool ID
    userPoolId: 'eu-west-1_lLibP7nAB',
    // OPTIONAL - Amazon Cognito Web Client ID
    userPoolWebClientId: 'mv8tvtu2ief73mml79i079top',
    // authenticationFlowType: 'USER_SRP_AUTH',
  },
}
