// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const awsConfig = {
  aws_project_region: 'eu-west-1',
  aws_cognito_identity_pool_id: 'eu-west-1:027d449a-b82b-4bd8-8fdb-981895db3398',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_lLibP7nAB',
  aws_user_pools_web_client_id: '7lhlkkfbfb4q5kpp90urffao',
  oauth: {
    domain: 'sandertest.auth.eu-west-1.amazoncognito.com',
    scope: [ 'phone', 'email', 'openid', 'profile', 'aws.cognito.signin.user.admin' ],
    redirectSignIn: 'http://localhost:3000/',
    redirectSignOut: 'http://localhost:3000/',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
}
